//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DiscordAngryBot.MessageHandlers {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.6.0.0")]
    internal sealed partial class CommandSettings : global::System.Configuration.ApplicationSettingsBase {
        
        private static CommandSettings defaultInstance = ((CommandSettings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new CommandSettings())));
        
        public static CommandSettings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("60000")]
        public int MinuteToMilliseconds {
            get {
                return ((int)(this["MinuteToMilliseconds"]));
            }
            set {
                this["MinuteToMilliseconds"] = value;
            }
        }
    }
}
