//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DiscordAngryBot.MessageHandlers {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class CommandResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CommandResources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DiscordAngryBot.MessageHandlers.CommandResources", typeof(CommandResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Добавлен новый администратор бота на сервере: &apos;{0}&apos;..
        /// </summary>
        internal static string AdminAddedLine {
            get {
                return ResourceManager.GetString("AdminAddedLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Забраны администраторские права у: &apos;{0}&apos;..
        /// </summary>
        internal static string AdminRemovedLine {
            get {
                return ResourceManager.GetString("AdminRemovedLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Данный пользователь уже является администратором..
        /// </summary>
        internal static string AlreadyAdminLine {
            get {
                return ResourceManager.GetString("AlreadyAdminLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Роль для бана на этом сервере: &apos;{0}&apos;.
        /// </summary>
        internal static string BanRoleSetLine {
            get {
                return ResourceManager.GetString("BanRoleSetLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Префикс команд сменен на &apos;{0}&apos;..
        /// </summary>
        internal static string CommandPrefixChangedLine {
            get {
                return ResourceManager.GetString("CommandPrefixChangedLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Данная команда не предназначена для использования в данном контексте..
        /// </summary>
        internal static string InvalidLocationScopeLine {
            get {
                return ResourceManager.GetString("InvalidLocationScopeLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Не получилось удалить столько сообщений, возможно, вы попытались удалить сообщения старше двух недель..
        /// </summary>
        internal static string InvalidMessageClearRangeLine {
            get {
                return ResourceManager.GetString("InvalidMessageClearRangeLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Этот канал установлен как новостной..
        /// </summary>
        internal static string NewsChannelSetLine {
            get {
                return ResourceManager.GetString("NewsChannelSetLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Данный пользователь не является администратором..
        /// </summary>
        internal static string NotAnAdminLine {
            get {
                return ResourceManager.GetString("NotAnAdminLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Матфильтр на этом сервере выключен..
        /// </summary>
        internal static string SwearFilterDisabledLine {
            get {
                return ResourceManager.GetString("SwearFilterDisabledLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Матфильтр на этом сервере включен..
        /// </summary>
        internal static string SwearFilterEnabledLine {
            get {
                return ResourceManager.GetString("SwearFilterEnabledLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Пользователь {0} не был забанен..
        /// </summary>
        internal static string UserIsNotBannedLine {
            get {
                return ResourceManager.GetString("UserIsNotBannedLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Пользователь {0} был разбанен..
        /// </summary>
        internal static string UserIsUnbannedLine {
            get {
                return ResourceManager.GetString("UserIsUnbannedLine", resourceCulture);
            }
        }
    }
}
